### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/collections-ui#79]
I would like to know if this project has been replaced by https://github.com/DINA-Web/dina-collections-ui ?

**Comment by mikkohei13** [comment]
Yes, this has been replaced with dina-collections-ui, which we started to develop about a month ago. The page https://github.com/DINA-Web/documentation/wiki/Technical-manual lists currently active repositories.

**Comment by cgendreau** [comment]
Thanks @mikkohei13 
Can we update the README with this information?
